input {
  beats {
    port => 5044
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "centralized-logs-%{+YYYY.MM.dd}"
    # --> REMOVED the user and password lines <--
  }
  file {
    path => "/output-logs/centralized.log"
    codec => "json_lines"
  }
  stdout { codec => rubydebug }
}