version: "3.8"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:8.13.0
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
            ELASTICSEARCH_USERNAME: "kibana_system"
            ELASTICSEARCH_PASSWORD: "" # Not needed, but must be set empty
            KBN_INTERACTIVE_SETUP_ENABLED: "false"
        depends_on:
            - elasticsearch

    logstash:
        image: docker.elastic.co/logstash/logstash:8.13.0
        container_name: logstash
        ports:
            - "5044:5044"
            - "5000:5000"
            - "9600:9600"
            - "8080:8080"
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline
            - ./logstash/logs:/logs
        depends_on:
            - elasticsearch
